//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("ProModel", "FK_BasicInfo_Manager", "Manager", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcApp.Models.Manager), "BasicInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApp.Models.BasicInfo), true)]
[assembly: EdmRelationshipAttribute("ProModel", "FK_EmergencyInfo_BasicInfo", "BasicInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcApp.Models.BasicInfo), "EmergencyInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApp.Models.EmergencyInfo), true)]
[assembly: EdmRelationshipAttribute("ProModel", "FK_HealthPlan_BasicInfo", "BasicInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcApp.Models.BasicInfo), "HealthPlan", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApp.Models.HealthPlan), true)]
[assembly: EdmRelationshipAttribute("ProModel", "FK_Location_BasicInfo", "BasicInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcApp.Models.BasicInfo), "Location", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApp.Models.Location), true)]
[assembly: EdmRelationshipAttribute("ProModel", "FK_HealthIndicator_BasicInfo", "BasicInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcApp.Models.BasicInfo), "HealthIndicator", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApp.Models.HealthIndicator), true)]

#endregion

namespace MvcApp.Models
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class ProEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“ProEntities”部分中的连接字符串初始化新 ProEntities 对象。
        /// </summary>
        public ProEntities() : base("name=ProEntities", "ProEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ProEntities 对象。
        /// </summary>
        public ProEntities(string connectionString) : base(connectionString, "ProEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ProEntities 对象。
        /// </summary>
        public ProEntities(EntityConnection connection) : base(connection, "ProEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<BasicInfo> BasicInfo
        {
            get
            {
                if ((_BasicInfo == null))
                {
                    _BasicInfo = base.CreateObjectSet<BasicInfo>("BasicInfo");
                }
                return _BasicInfo;
            }
        }
        private ObjectSet<BasicInfo> _BasicInfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<EmergencyInfo> EmergencyInfo
        {
            get
            {
                if ((_EmergencyInfo == null))
                {
                    _EmergencyInfo = base.CreateObjectSet<EmergencyInfo>("EmergencyInfo");
                }
                return _EmergencyInfo;
            }
        }
        private ObjectSet<EmergencyInfo> _EmergencyInfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<HealthPlan> HealthPlan
        {
            get
            {
                if ((_HealthPlan == null))
                {
                    _HealthPlan = base.CreateObjectSet<HealthPlan>("HealthPlan");
                }
                return _HealthPlan;
            }
        }
        private ObjectSet<HealthPlan> _HealthPlan;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Location> Location
        {
            get
            {
                if ((_Location == null))
                {
                    _Location = base.CreateObjectSet<Location>("Location");
                }
                return _Location;
            }
        }
        private ObjectSet<Location> _Location;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Manager> Manager
        {
            get
            {
                if ((_Manager == null))
                {
                    _Manager = base.CreateObjectSet<Manager>("Manager");
                }
                return _Manager;
            }
        }
        private ObjectSet<Manager> _Manager;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<HealthIndicator> HealthIndicator
        {
            get
            {
                if ((_HealthIndicator == null))
                {
                    _HealthIndicator = base.CreateObjectSet<HealthIndicator>("HealthIndicator");
                }
                return _HealthIndicator;
            }
        }
        private ObjectSet<HealthIndicator> _HealthIndicator;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 BasicInfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToBasicInfo(BasicInfo basicInfo)
        {
            base.AddObject("BasicInfo", basicInfo);
        }
    
        /// <summary>
        /// 用于向 EmergencyInfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToEmergencyInfo(EmergencyInfo emergencyInfo)
        {
            base.AddObject("EmergencyInfo", emergencyInfo);
        }
    
        /// <summary>
        /// 用于向 HealthPlan EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToHealthPlan(HealthPlan healthPlan)
        {
            base.AddObject("HealthPlan", healthPlan);
        }
    
        /// <summary>
        /// 用于向 Location EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToLocation(Location location)
        {
            base.AddObject("Location", location);
        }
    
        /// <summary>
        /// 用于向 Manager EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToManager(Manager manager)
        {
            base.AddObject("Manager", manager);
        }
    
        /// <summary>
        /// 用于向 HealthIndicator EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToHealthIndicator(HealthIndicator healthIndicator)
        {
            base.AddObject("HealthIndicator", healthIndicator);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProModel", Name="BasicInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BasicInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 BasicInfo 对象。
        /// </summary>
        /// <param name="iD_User">ID_User 属性的初始值。</param>
        /// <param name="iD_Manager">ID_Manager 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="age">Age 属性的初始值。</param>
        /// <param name="sex">Sex 属性的初始值。</param>
        /// <param name="marrige">Marrige 属性的初始值。</param>
        /// <param name="telNum">TelNum 属性的初始值。</param>
        /// <param name="address">Address 属性的初始值。</param>
        /// <param name="children">Children 属性的初始值。</param>
        /// <param name="hobby">Hobby 属性的初始值。</param>
        /// <param name="userName">UserName 属性的初始值。</param>
        /// <param name="userPassword">UserPassword 属性的初始值。</param>
        public static BasicInfo CreateBasicInfo(/*global::System.Int64 iD_User,*/ global::System.Int64 iD_Manager, global::System.String name, global::System.Int16 age, global::System.Boolean sex, global::System.Boolean marrige, global::System.String telNum, global::System.String address, global::System.String children, global::System.String hobby, global::System.String userName, global::System.String userPassword)
        {
            BasicInfo basicInfo = new BasicInfo();
            //basicInfo.ID_User = iD_User;
            basicInfo.ID_Manager = iD_Manager;
            basicInfo.Name = name;
            basicInfo.Age = age;
            basicInfo.Sex = sex;
            basicInfo.Marrige = marrige;
            basicInfo.TelNum = telNum;
            basicInfo.Address = address;
            basicInfo.Children = children;
            basicInfo.Hobby = hobby;
            basicInfo.UserName = userName;
            basicInfo.UserPassword = userPassword;
            return basicInfo;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID_User
        {
            get
            {
                return _ID_User;
            }
            set
            {
                if (_ID_User != value)
                {
                    OnID_UserChanging(value);
                    ReportPropertyChanging("ID_User");
                    _ID_User = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_User");
                    OnID_UserChanged();
                }
            }
        }
        private global::System.Int64 _ID_User;
        partial void OnID_UserChanging(global::System.Int64 value);
        partial void OnID_UserChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID_Manager
        {
            get
            {
                return _ID_Manager;
            }
            set
            {
                OnID_ManagerChanging(value);
                ReportPropertyChanging("ID_Manager");
                _ID_Manager = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Manager");
                OnID_ManagerChanged();
            }
        }
        private global::System.Int64 _ID_Manager;
        partial void OnID_ManagerChanging(global::System.Int64 value);
        partial void OnID_ManagerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private global::System.Int16 _Age;
        partial void OnAgeChanging(global::System.Int16 value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Sex
        {
            get
            {
                return _Sex;
            }
            set
            {
                OnSexChanging(value);
                ReportPropertyChanging("Sex");
                _Sex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sex");
                OnSexChanged();
            }
        }
        private global::System.Boolean _Sex;
        partial void OnSexChanging(global::System.Boolean value);
        partial void OnSexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Marrige
        {
            get
            {
                return _Marrige;
            }
            set
            {
                OnMarrigeChanging(value);
                ReportPropertyChanging("Marrige");
                _Marrige = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Marrige");
                OnMarrigeChanged();
            }
        }
        private global::System.Boolean _Marrige;
        partial void OnMarrigeChanging(global::System.Boolean value);
        partial void OnMarrigeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TelNum
        {
            get
            {
                return _TelNum;
            }
            set
            {
                OnTelNumChanging(value);
                ReportPropertyChanging("TelNum");
                _TelNum = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TelNum");
                OnTelNumChanged();
            }
        }
        private global::System.String _TelNum;
        partial void OnTelNumChanging(global::System.String value);
        partial void OnTelNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Children
        {
            get
            {
                return _Children;
            }
            set
            {
                OnChildrenChanging(value);
                ReportPropertyChanging("Children");
                _Children = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Children");
                OnChildrenChanged();
            }
        }
        private global::System.String _Children;
        partial void OnChildrenChanging(global::System.String value);
        partial void OnChildrenChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Hobby
        {
            get
            {
                return _Hobby;
            }
            set
            {
                OnHobbyChanging(value);
                ReportPropertyChanging("Hobby");
                _Hobby = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Hobby");
                OnHobbyChanged();
            }
        }
        private global::System.String _Hobby;
        partial void OnHobbyChanging(global::System.String value);
        partial void OnHobbyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Image
        {
            get
            {
                return StructuralObject.GetValidValue(_Image);
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.Byte[] _Image;
        partial void OnImageChanging(global::System.Byte[] value);
        partial void OnImageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserPassword
        {
            get
            {
                return _UserPassword;
            }
            set
            {
                OnUserPasswordChanging(value);
                ReportPropertyChanging("UserPassword");
                _UserPassword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserPassword");
                OnUserPasswordChanged();
            }
        }
        private global::System.String _UserPassword;
        partial void OnUserPasswordChanging(global::System.String value);
        partial void OnUserPasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> BloodThreshold
        {
            get
            {
                return _BloodThreshold;
            }
            set
            {
                OnBloodThresholdChanging(value);
                ReportPropertyChanging("BloodThreshold");
                _BloodThreshold = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BloodThreshold");
                OnBloodThresholdChanged();
            }
        }
        private Nullable<global::System.Int16> _BloodThreshold;
        partial void OnBloodThresholdChanging(Nullable<global::System.Int16> value);
        partial void OnBloodThresholdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> GlucoseThreshold
        {
            get
            {
                return _GlucoseThreshold;
            }
            set
            {
                OnGlucoseThresholdChanging(value);
                ReportPropertyChanging("GlucoseThreshold");
                _GlucoseThreshold = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GlucoseThreshold");
                OnGlucoseThresholdChanged();
            }
        }
        private Nullable<global::System.Int16> _GlucoseThreshold;
        partial void OnGlucoseThresholdChanging(Nullable<global::System.Int16> value);
        partial void OnGlucoseThresholdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> TempThreshold
        {
            get
            {
                return _TempThreshold;
            }
            set
            {
                OnTempThresholdChanging(value);
                ReportPropertyChanging("TempThreshold");
                _TempThreshold = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TempThreshold");
                OnTempThresholdChanged();
            }
        }
        private Nullable<global::System.Int16> _TempThreshold;
        partial void OnTempThresholdChanging(Nullable<global::System.Int16> value);
        partial void OnTempThresholdChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProModel", "FK_BasicInfo_Manager", "Manager")]
        public Manager Manager
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Manager>("ProModel.FK_BasicInfo_Manager", "Manager").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Manager>("ProModel.FK_BasicInfo_Manager", "Manager").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Manager> ManagerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Manager>("ProModel.FK_BasicInfo_Manager", "Manager");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Manager>("ProModel.FK_BasicInfo_Manager", "Manager", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProModel", "FK_EmergencyInfo_BasicInfo", "EmergencyInfo")]
        public EntityCollection<EmergencyInfo> EmergencyInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EmergencyInfo>("ProModel.FK_EmergencyInfo_BasicInfo", "EmergencyInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EmergencyInfo>("ProModel.FK_EmergencyInfo_BasicInfo", "EmergencyInfo", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProModel", "FK_HealthPlan_BasicInfo", "HealthPlan")]
        public EntityCollection<HealthPlan> HealthPlan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HealthPlan>("ProModel.FK_HealthPlan_BasicInfo", "HealthPlan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HealthPlan>("ProModel.FK_HealthPlan_BasicInfo", "HealthPlan", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProModel", "FK_Location_BasicInfo", "Location")]
        public EntityCollection<Location> Location
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Location>("ProModel.FK_Location_BasicInfo", "Location");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Location>("ProModel.FK_Location_BasicInfo", "Location", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProModel", "FK_HealthIndicator_BasicInfo", "HealthIndicator")]
        public EntityCollection<HealthIndicator> HealthIndicator
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HealthIndicator>("ProModel.FK_HealthIndicator_BasicInfo", "HealthIndicator");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HealthIndicator>("ProModel.FK_HealthIndicator_BasicInfo", "HealthIndicator", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProModel", Name="EmergencyInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EmergencyInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 EmergencyInfo 对象。
        /// </summary>
        /// <param name="iD_Emergency">ID_Emergency 属性的初始值。</param>
        /// <param name="iD_User">ID_User 属性的初始值。</param>
        /// <param name="location">Location 属性的初始值。</param>
        /// <param name="emergencyDate">EmergencyDate 属性的初始值。</param>
        /// <param name="staff">Staff 属性的初始值。</param>
        /// <param name="illnessAnalyses">IllnessAnalyses 属性的初始值。</param>
        /// <param name="medicalResult">MedicalResult 属性的初始值。</param>
        /// <param name="advice">Advice 属性的初始值。</param>
        public static EmergencyInfo CreateEmergencyInfo(global::System.Int64 iD_Emergency, global::System.Int64 iD_User, global::System.String location, global::System.DateTime emergencyDate, global::System.String staff, global::System.String illnessAnalyses, global::System.String medicalResult, global::System.String advice)
        {
            EmergencyInfo emergencyInfo = new EmergencyInfo();
            emergencyInfo.ID_Emergency = iD_Emergency;
            emergencyInfo.ID_User = iD_User;
            emergencyInfo.Location = location;
            emergencyInfo.EmergencyDate = emergencyDate;
            emergencyInfo.Staff = staff;
            emergencyInfo.IllnessAnalyses = illnessAnalyses;
            emergencyInfo.MedicalResult = medicalResult;
            emergencyInfo.Advice = advice;
            return emergencyInfo;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID_Emergency
        {
            get
            {
                return _ID_Emergency;
            }
            set
            {
                if (_ID_Emergency != value)
                {
                    OnID_EmergencyChanging(value);
                    ReportPropertyChanging("ID_Emergency");
                    _ID_Emergency = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Emergency");
                    OnID_EmergencyChanged();
                }
            }
        }
        private global::System.Int64 _ID_Emergency;
        partial void OnID_EmergencyChanging(global::System.Int64 value);
        partial void OnID_EmergencyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID_User
        {
            get
            {
                return _ID_User;
            }
            set
            {
                OnID_UserChanging(value);
                ReportPropertyChanging("ID_User");
                _ID_User = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_User");
                OnID_UserChanged();
            }
        }
        private global::System.Int64 _ID_User;
        partial void OnID_UserChanging(global::System.Int64 value);
        partial void OnID_UserChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EmergencyDate
        {
            get
            {
                return _EmergencyDate;
            }
            set
            {
                OnEmergencyDateChanging(value);
                ReportPropertyChanging("EmergencyDate");
                _EmergencyDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmergencyDate");
                OnEmergencyDateChanged();
            }
        }
        private global::System.DateTime _EmergencyDate;
        partial void OnEmergencyDateChanging(global::System.DateTime value);
        partial void OnEmergencyDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Staff
        {
            get
            {
                return _Staff;
            }
            set
            {
                OnStaffChanging(value);
                ReportPropertyChanging("Staff");
                _Staff = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Staff");
                OnStaffChanged();
            }
        }
        private global::System.String _Staff;
        partial void OnStaffChanging(global::System.String value);
        partial void OnStaffChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IllnessAnalyses
        {
            get
            {
                return _IllnessAnalyses;
            }
            set
            {
                OnIllnessAnalysesChanging(value);
                ReportPropertyChanging("IllnessAnalyses");
                _IllnessAnalyses = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IllnessAnalyses");
                OnIllnessAnalysesChanged();
            }
        }
        private global::System.String _IllnessAnalyses;
        partial void OnIllnessAnalysesChanging(global::System.String value);
        partial void OnIllnessAnalysesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MedicalResult
        {
            get
            {
                return _MedicalResult;
            }
            set
            {
                OnMedicalResultChanging(value);
                ReportPropertyChanging("MedicalResult");
                _MedicalResult = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MedicalResult");
                OnMedicalResultChanged();
            }
        }
        private global::System.String _MedicalResult;
        partial void OnMedicalResultChanging(global::System.String value);
        partial void OnMedicalResultChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Advice
        {
            get
            {
                return _Advice;
            }
            set
            {
                OnAdviceChanging(value);
                ReportPropertyChanging("Advice");
                _Advice = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Advice");
                OnAdviceChanged();
            }
        }
        private global::System.String _Advice;
        partial void OnAdviceChanging(global::System.String value);
        partial void OnAdviceChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProModel", "FK_EmergencyInfo_BasicInfo", "BasicInfo")]
        public BasicInfo BasicInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BasicInfo>("ProModel.FK_EmergencyInfo_BasicInfo", "BasicInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BasicInfo>("ProModel.FK_EmergencyInfo_BasicInfo", "BasicInfo").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BasicInfo> BasicInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BasicInfo>("ProModel.FK_EmergencyInfo_BasicInfo", "BasicInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BasicInfo>("ProModel.FK_EmergencyInfo_BasicInfo", "BasicInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProModel", Name="HealthIndicator")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HealthIndicator : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 HealthIndicator 对象。
        /// </summary>
        /// <param name="iD_HealthIndica">ID_HealthIndica 属性的初始值。</param>
        /// <param name="iD_User">ID_User 属性的初始值。</param>
        /// <param name="bloodPressure">BloodPressure 属性的初始值。</param>
        /// <param name="bloodGlucose">BloodGlucose 属性的初始值。</param>
        /// <param name="duration">Duration 属性的初始值。</param>
        /// <param name="calorie">Calorie 属性的初始值。</param>
        /// <param name="distance">Distance 属性的初始值。</param>
        /// <param name="heartBeat">HeartBeat 属性的初始值。</param>
        /// <param name="date">Date 属性的初始值。</param>
        public static HealthIndicator CreateHealthIndicator(global::System.Int64 iD_HealthIndica, global::System.Int64 iD_User, global::System.Int16 bloodPressure, global::System.Int16 bloodGlucose, global::System.Int16 duration, global::System.Int16 calorie, global::System.Int16 distance, global::System.Int16 heartBeat, global::System.DateTime date)
        {
            HealthIndicator healthIndicator = new HealthIndicator();
            healthIndicator.ID_HealthIndica = iD_HealthIndica;
            healthIndicator.ID_User = iD_User;
            healthIndicator.BloodPressure = bloodPressure;
            healthIndicator.BloodGlucose = bloodGlucose;
            healthIndicator.Duration = duration;
            healthIndicator.Calorie = calorie;
            healthIndicator.Distance = distance;
            healthIndicator.HeartBeat = heartBeat;
            healthIndicator.Date = date;
            return healthIndicator;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID_HealthIndica
        {
            get
            {
                return _ID_HealthIndica;
            }
            set
            {
                if (_ID_HealthIndica != value)
                {
                    OnID_HealthIndicaChanging(value);
                    ReportPropertyChanging("ID_HealthIndica");
                    _ID_HealthIndica = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_HealthIndica");
                    OnID_HealthIndicaChanged();
                }
            }
        }
        private global::System.Int64 _ID_HealthIndica;
        partial void OnID_HealthIndicaChanging(global::System.Int64 value);
        partial void OnID_HealthIndicaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID_User
        {
            get
            {
                return _ID_User;
            }
            set
            {
                OnID_UserChanging(value);
                ReportPropertyChanging("ID_User");
                _ID_User = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_User");
                OnID_UserChanged();
            }
        }
        private global::System.Int64 _ID_User;
        partial void OnID_UserChanging(global::System.Int64 value);
        partial void OnID_UserChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 BloodPressure
        {
            get
            {
                return _BloodPressure;
            }
            set
            {
                OnBloodPressureChanging(value);
                ReportPropertyChanging("BloodPressure");
                _BloodPressure = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BloodPressure");
                OnBloodPressureChanged();
            }
        }
        private global::System.Int16 _BloodPressure;
        partial void OnBloodPressureChanging(global::System.Int16 value);
        partial void OnBloodPressureChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 BloodGlucose
        {
            get
            {
                return _BloodGlucose;
            }
            set
            {
                OnBloodGlucoseChanging(value);
                ReportPropertyChanging("BloodGlucose");
                _BloodGlucose = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BloodGlucose");
                OnBloodGlucoseChanged();
            }
        }
        private global::System.Int16 _BloodGlucose;
        partial void OnBloodGlucoseChanging(global::System.Int16 value);
        partial void OnBloodGlucoseChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Duration
        {
            get
            {
                return _Duration;
            }
            set
            {
                OnDurationChanging(value);
                ReportPropertyChanging("Duration");
                _Duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Duration");
                OnDurationChanged();
            }
        }
        private global::System.Int16 _Duration;
        partial void OnDurationChanging(global::System.Int16 value);
        partial void OnDurationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Calorie
        {
            get
            {
                return _Calorie;
            }
            set
            {
                OnCalorieChanging(value);
                ReportPropertyChanging("Calorie");
                _Calorie = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Calorie");
                OnCalorieChanged();
            }
        }
        private global::System.Int16 _Calorie;
        partial void OnCalorieChanging(global::System.Int16 value);
        partial void OnCalorieChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Distance
        {
            get
            {
                return _Distance;
            }
            set
            {
                OnDistanceChanging(value);
                ReportPropertyChanging("Distance");
                _Distance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Distance");
                OnDistanceChanged();
            }
        }
        private global::System.Int16 _Distance;
        partial void OnDistanceChanging(global::System.Int16 value);
        partial void OnDistanceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 HeartBeat
        {
            get
            {
                return _HeartBeat;
            }
            set
            {
                OnHeartBeatChanging(value);
                ReportPropertyChanging("HeartBeat");
                _HeartBeat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HeartBeat");
                OnHeartBeatChanged();
            }
        }
        private global::System.Int16 _HeartBeat;
        partial void OnHeartBeatChanging(global::System.Int16 value);
        partial void OnHeartBeatChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProModel", "FK_HealthIndicator_BasicInfo", "BasicInfo")]
        public BasicInfo BasicInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BasicInfo>("ProModel.FK_HealthIndicator_BasicInfo", "BasicInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BasicInfo>("ProModel.FK_HealthIndicator_BasicInfo", "BasicInfo").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BasicInfo> BasicInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BasicInfo>("ProModel.FK_HealthIndicator_BasicInfo", "BasicInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BasicInfo>("ProModel.FK_HealthIndicator_BasicInfo", "BasicInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProModel", Name="HealthPlan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HealthPlan : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 HealthPlan 对象。
        /// </summary>
        /// <param name="iD_Plan">ID_Plan 属性的初始值。</param>
        /// <param name="iD_User">ID_User 属性的初始值。</param>
        /// <param name="recipes">Recipes 属性的初始值。</param>
        /// <param name="movement">Movement 属性的初始值。</param>
        /// <param name="schedule">Schedule 属性的初始值。</param>
        public static HealthPlan CreateHealthPlan(global::System.Int64 iD_Plan, global::System.Int64 iD_User, global::System.String recipes, global::System.String movement, global::System.String schedule)
        {
            HealthPlan healthPlan = new HealthPlan();
            healthPlan.ID_Plan = iD_Plan;
            healthPlan.ID_User = iD_User;
            healthPlan.Recipes = recipes;
            healthPlan.Movement = movement;
            healthPlan.Schedule = schedule;
            return healthPlan;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID_Plan
        {
            get
            {
                return _ID_Plan;
            }
            set
            {
                if (_ID_Plan != value)
                {
                    OnID_PlanChanging(value);
                    ReportPropertyChanging("ID_Plan");
                    _ID_Plan = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Plan");
                    OnID_PlanChanged();
                }
            }
        }
        private global::System.Int64 _ID_Plan;
        partial void OnID_PlanChanging(global::System.Int64 value);
        partial void OnID_PlanChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID_User
        {
            get
            {
                return _ID_User;
            }
            set
            {
                OnID_UserChanging(value);
                ReportPropertyChanging("ID_User");
                _ID_User = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_User");
                OnID_UserChanged();
            }
        }
        private global::System.Int64 _ID_User;
        partial void OnID_UserChanging(global::System.Int64 value);
        partial void OnID_UserChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Recipes
        {
            get
            {
                return _Recipes;
            }
            set
            {
                OnRecipesChanging(value);
                ReportPropertyChanging("Recipes");
                _Recipes = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Recipes");
                OnRecipesChanged();
            }
        }
        private global::System.String _Recipes;
        partial void OnRecipesChanging(global::System.String value);
        partial void OnRecipesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Movement
        {
            get
            {
                return _Movement;
            }
            set
            {
                OnMovementChanging(value);
                ReportPropertyChanging("Movement");
                _Movement = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Movement");
                OnMovementChanged();
            }
        }
        private global::System.String _Movement;
        partial void OnMovementChanging(global::System.String value);
        partial void OnMovementChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Schedule
        {
            get
            {
                return _Schedule;
            }
            set
            {
                OnScheduleChanging(value);
                ReportPropertyChanging("Schedule");
                _Schedule = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Schedule");
                OnScheduleChanged();
            }
        }
        private global::System.String _Schedule;
        partial void OnScheduleChanging(global::System.String value);
        partial void OnScheduleChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProModel", "FK_HealthPlan_BasicInfo", "BasicInfo")]
        public BasicInfo BasicInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BasicInfo>("ProModel.FK_HealthPlan_BasicInfo", "BasicInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BasicInfo>("ProModel.FK_HealthPlan_BasicInfo", "BasicInfo").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BasicInfo> BasicInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BasicInfo>("ProModel.FK_HealthPlan_BasicInfo", "BasicInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BasicInfo>("ProModel.FK_HealthPlan_BasicInfo", "BasicInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProModel", Name="Location")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Location : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Location 对象。
        /// </summary>
        /// <param name="iD_Location">ID_Location 属性的初始值。</param>
        /// <param name="iD_User">ID_User 属性的初始值。</param>
        /// <param name="dataTime">DataTime 属性的初始值。</param>
        /// <param name="longitude">Longitude 属性的初始值。</param>
        /// <param name="latitude">Latitude 属性的初始值。</param>
        public static Location CreateLocation(global::System.Int64 iD_Location, global::System.Int64 iD_User, global::System.DateTime dataTime, global::System.Double longitude, global::System.Double latitude)
        {
            Location location = new Location();
            location.ID_Location = iD_Location;
            location.ID_User = iD_User;
            location.DataTime = dataTime;
            location.Longitude = longitude;
            location.Latitude = latitude;
            return location;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID_Location
        {
            get
            {
                return _ID_Location;
            }
            set
            {
                if (_ID_Location != value)
                {
                    OnID_LocationChanging(value);
                    ReportPropertyChanging("ID_Location");
                    _ID_Location = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Location");
                    OnID_LocationChanged();
                }
            }
        }
        private global::System.Int64 _ID_Location;
        partial void OnID_LocationChanging(global::System.Int64 value);
        partial void OnID_LocationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID_User
        {
            get
            {
                return _ID_User;
            }
            set
            {
                OnID_UserChanging(value);
                ReportPropertyChanging("ID_User");
                _ID_User = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_User");
                OnID_UserChanged();
            }
        }
        private global::System.Int64 _ID_User;
        partial void OnID_UserChanging(global::System.Int64 value);
        partial void OnID_UserChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataTime
        {
            get
            {
                return _DataTime;
            }
            set
            {
                OnDataTimeChanging(value);
                ReportPropertyChanging("DataTime");
                _DataTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataTime");
                OnDataTimeChanged();
            }
        }
        private global::System.DateTime _DataTime;
        partial void OnDataTimeChanging(global::System.DateTime value);
        partial void OnDataTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.Double _Longitude;
        partial void OnLongitudeChanging(global::System.Double value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.Double _Latitude;
        partial void OnLatitudeChanging(global::System.Double value);
        partial void OnLatitudeChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProModel", "FK_Location_BasicInfo", "BasicInfo")]
        public BasicInfo BasicInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BasicInfo>("ProModel.FK_Location_BasicInfo", "BasicInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BasicInfo>("ProModel.FK_Location_BasicInfo", "BasicInfo").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BasicInfo> BasicInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BasicInfo>("ProModel.FK_Location_BasicInfo", "BasicInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BasicInfo>("ProModel.FK_Location_BasicInfo", "BasicInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProModel", Name="Manager")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Manager : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Manager 对象。
        /// </summary>
        /// <param name="iD_Manager">ID_Manager 属性的初始值。</param>
        /// <param name="man_Name">Man_Name 属性的初始值。</param>
        /// <param name="man_Sex">Man_Sex 属性的初始值。</param>
        /// <param name="man_Age">Man_Age 属性的初始值。</param>
        /// <param name="man_Tel">Man_Tel 属性的初始值。</param>
        /// <param name="man_Add">Man_Add 属性的初始值。</param>
        /// <param name="sysManIdentify">SysManIdentify 属性的初始值。</param>
        /// <param name="manName">ManName 属性的初始值。</param>
        /// <param name="manPassword">ManPassword 属性的初始值。</param>
        public static Manager CreateManager(/*global::System.Int64 iD_Manager,*/ global::System.String man_Name, global::System.Boolean man_Sex, global::System.Int16 man_Age, global::System.String man_Tel, global::System.String man_Add, global::System.Boolean sysManIdentify, global::System.String manName, global::System.String manPassword)
        {
            Manager manager = new Manager();
            //manager.ID_Manager = iD_Manager;
            manager.Man_Name = man_Name;
            manager.Man_Sex = man_Sex;
            manager.Man_Age = man_Age;
            manager.Man_Tel = man_Tel;
            manager.Man_Add = man_Add;
            manager.SysManIdentify = sysManIdentify;
            manager.ManName = manName;
            manager.ManPassword = manPassword;
            return manager;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID_Manager
        {
            get
            {
                return _ID_Manager;
            }
            set
            {
                if (_ID_Manager != value)
                {
                    OnID_ManagerChanging(value);
                    ReportPropertyChanging("ID_Manager");
                    _ID_Manager = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Manager");
                    OnID_ManagerChanged();
                }
            }
        }
        private global::System.Int64 _ID_Manager;
        partial void OnID_ManagerChanging(global::System.Int64 value);
        partial void OnID_ManagerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Man_Name
        {
            get
            {
                return _Man_Name;
            }
            set
            {
                OnMan_NameChanging(value);
                ReportPropertyChanging("Man_Name");
                _Man_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Man_Name");
                OnMan_NameChanged();
            }
        }
        private global::System.String _Man_Name;
        partial void OnMan_NameChanging(global::System.String value);
        partial void OnMan_NameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Man_Sex
        {
            get
            {
                return _Man_Sex;
            }
            set
            {
                OnMan_SexChanging(value);
                ReportPropertyChanging("Man_Sex");
                _Man_Sex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Man_Sex");
                OnMan_SexChanged();
            }
        }
        private global::System.Boolean _Man_Sex;
        partial void OnMan_SexChanging(global::System.Boolean value);
        partial void OnMan_SexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Man_Age
        {
            get
            {
                return _Man_Age;
            }
            set
            {
                OnMan_AgeChanging(value);
                ReportPropertyChanging("Man_Age");
                _Man_Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Man_Age");
                OnMan_AgeChanged();
            }
        }
        private global::System.Int16 _Man_Age;
        partial void OnMan_AgeChanging(global::System.Int16 value);
        partial void OnMan_AgeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Man_Tel
        {
            get
            {
                return _Man_Tel;
            }
            set
            {
                OnMan_TelChanging(value);
                ReportPropertyChanging("Man_Tel");
                _Man_Tel = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Man_Tel");
                OnMan_TelChanged();
            }
        }
        private global::System.String _Man_Tel;
        partial void OnMan_TelChanging(global::System.String value);
        partial void OnMan_TelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Man_Add
        {
            get
            {
                return _Man_Add;
            }
            set
            {
                OnMan_AddChanging(value);
                ReportPropertyChanging("Man_Add");
                _Man_Add = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Man_Add");
                OnMan_AddChanged();
            }
        }
        private global::System.String _Man_Add;
        partial void OnMan_AddChanging(global::System.String value);
        partial void OnMan_AddChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean SysManIdentify
        {
            get
            {
                return _SysManIdentify;
            }
            set
            {
                OnSysManIdentifyChanging(value);
                ReportPropertyChanging("SysManIdentify");
                _SysManIdentify = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysManIdentify");
                OnSysManIdentifyChanged();
            }
        }
        private global::System.Boolean _SysManIdentify;
        partial void OnSysManIdentifyChanging(global::System.Boolean value);
        partial void OnSysManIdentifyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ManName
        {
            get
            {
                return _ManName;
            }
            set
            {
                OnManNameChanging(value);
                ReportPropertyChanging("ManName");
                _ManName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ManName");
                OnManNameChanged();
            }
        }
        private global::System.String _ManName;
        partial void OnManNameChanging(global::System.String value);
        partial void OnManNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ManPassword
        {
            get
            {
                return _ManPassword;
            }
            set
            {
                OnManPasswordChanging(value);
                ReportPropertyChanging("ManPassword");
                _ManPassword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ManPassword");
                OnManPasswordChanged();
            }
        }
        private global::System.String _ManPassword;
        partial void OnManPasswordChanging(global::System.String value);
        partial void OnManPasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> GroupNum
        {
            get
            {
                return _GroupNum;
            }
            set
            {
                OnGroupNumChanging(value);
                ReportPropertyChanging("GroupNum");
                _GroupNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupNum");
                OnGroupNumChanged();
            }
        }
        private Nullable<global::System.Int16> _GroupNum;
        partial void OnGroupNumChanging(Nullable<global::System.Int16> value);
        partial void OnGroupNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GroupPlan
        {
            get
            {
                return _GroupPlan;
            }
            set
            {
                OnGroupPlanChanging(value);
                ReportPropertyChanging("GroupPlan");
                _GroupPlan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GroupPlan");
                OnGroupPlanChanged();
            }
        }
        private global::System.String _GroupPlan;
        partial void OnGroupPlanChanging(global::System.String value);
        partial void OnGroupPlanChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] GroupPhoto
        {
            get
            {
                return StructuralObject.GetValidValue(_GroupPhoto);
            }
            set
            {
                OnGroupPhotoChanging(value);
                ReportPropertyChanging("GroupPhoto");
                _GroupPhoto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GroupPhoto");
                OnGroupPhotoChanged();
            }
        }
        private global::System.Byte[] _GroupPhoto;
        partial void OnGroupPhotoChanging(global::System.Byte[] value);
        partial void OnGroupPhotoChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProModel", "FK_BasicInfo_Manager", "BasicInfo")]
        public EntityCollection<BasicInfo> BasicInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BasicInfo>("ProModel.FK_BasicInfo_Manager", "BasicInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BasicInfo>("ProModel.FK_BasicInfo_Manager", "BasicInfo", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
